### ISSUE TITLE
Dapps does not work with SpaceSuit

### ISSUE THREAD

**Issue by svantetobias** [jamespic/SpaceSuit#17]
Thank you for a very useful tool! However, my favorite dapp https://dai.makerdao.com/ does not work with SpaceSuit, but works fine with MetaMask. Is it a websocket issue maybe?

**Comment by jamespic** [comment]
Hmm, I thought I'd fixed https://dai.makerdao.com/. This may sound crazy, but does it work if you wait for it to load, and then press F5?

**Comment by svantetobias** [comment]
It just loads forever. Seems to register my Ledger address though (displayed in the top left).

**Comment by jamespic** [comment]
That is surprising. I've had issues with Dai Dashboard before. There's a race condition in the Dai Dashboard where, if the contract balances load before it registers the ledger address, it doesn't update the address used to calculate the contract balances.

But SpaceSuit *should* cache the address list after the first time it's loaded (as long as "Use Hacks" is turned on), so it should win the race second time around.

At the moment, it's cached in `sessionStorage` so it's only cached per-tab. I'm wondering about changing this to use `localStorage` instead, so it caches it longer and per-site rather than per-tab.

I'll see if I can reproduce. I managed to use Dai Dashboard to wrap some Eth yesterday, so maybe the issue is intermittent.

**Comment by jamespic** [comment]
I've got an idea. If I can't make the address list load faster, I can make the contract balances load slower. I'll delay the `eth_getBlockByNumber` call (that the contract balances depend on) if there's an outstanding `eth_addresses` request. I'll try that out.

**Comment by svantetobias** [comment]
Not sure if you pushed out an update, but I got it to work just now! Playing with different combinations of Use Hacks, Debug and page refresh seemed to make it work consistently now (and actually significantly faster than MetaMask!).

**Comment by jamespic** [comment]
Glad you got it working! Can you remember what combination of options you were using when it wasn't working? I still want to put in a few changes to improve the UX on this, and it would be good to understand what didn't work first time.

**Comment by jamespic** [comment]
I've just committed some changes to help de-race the Dai dashboard startup, but I haven't got the changes for this into a release yet. I'm debating whether to push out a 0.2.9 release, or to hold fire and roll it into the 0.3.0 release.

**Comment by svantetobias** [comment]
I was not very structured in my approach, but I think it was not me not enabling Use Hacks which tripped me up. When I got it to work I also enabled Debug, so not sure if that helped or not.

**Comment by jamespic** [comment]
Ah, that makes sense. Cheers. You should be OK to disable Debug - all it'll do is output all requests and responses to the console, which might slow down some dapps, or use extra memory.
