### ISSUE TITLE
DAI dashboard not detecting the connection to Ethereum

### ISSUE THREAD

**Issue by djibix** [jamespic/SpaceSuit#7]
I tried to use SpaceSuit with https://dai.makerdao.com/ with no success. The page stays on "No connection to Ethereum".
If this is of any help, I can see this error in Chrome console:
`web3.js:14 Uncaught TypeError: Cannot set property web3 of #<Window> which has only a getter
    at s (web3.js:14)
    at G.init (App.jsx:277)`

The command `web3.eth.getAccounts(console.log)` returns the Ledger accounts correctly.
I can run other Dapps properly.
I'm not sure if it's a bug in SpaceSuit or some incompatibility with DAI dashboard...

**Comment by jamespic** [comment]
I've found the issue. A workaround I put in for buggy dapps is causing issues with well-written ones like DAI.

I've got a fix, but once the fix is in, I see the same sort of high CPU usage I get with OasisDEX, so I think I need to finally fix that too before I release a fix for this. If you can tolerate the high CPU usage, you can workaround the original issue by disabling "Use Hacks" in the options.

**Comment by jamespic** [comment]
So, with the workaround, it sort-of works, but there's a bug where balances show up as "Loading...".

This looks to be due to a race condition in the MakerDAO code - it initialises the default account with `web3.eth.getAccounts`, but doesn't wait for the call to return before using the result. This is no problem in MetaMask, since this method returns instantly, but it's a problem when account details have to be fetched from the hardware wallet, which can take a few seconds.

I should be able to adapt the account list caching behaviour that I use to implement synchronous calls to `eth_getAccounts`, but I'll need to think carefully about whether this risks breaking working dapps.

**Comment by jamespic** [comment]
This seems to work now (although I haven't gone as far as opening a CDP, or similar), so I'm closing the ticket - although please reopen if I've closed prematurely.
